spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://51.20.6.246:3306/techdb
    username: harsh_user
    password: Harsh@1904
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB     
